trigger:
- master
- release-*

extends:
  template: azure_templates/all.yml
  parameters:
    pythonVersions:
    - '3.6'
    - '3.7'
    - '3.8'
    platforms:
    - 'linux'
    - 'macos'
    - 'windows'